# Generated by Django 2.0.3 on 2018-07-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount1', models.IntegerField(blank=True, null=True)),
                ('amount2', models.IntegerField(blank=True, null=True)),
                ('h_index', models.IntegerField(blank=True, null=True)),
                ('core', models.CharField(blank=True, max_length=255, null=True)),
                ('cssci', models.CharField(blank=True, max_length=255, null=True)),
                ('rdfybkzl', models.CharField(blank=True, max_length=255, null=True)),
                ('co_expert', models.CharField(blank=True, max_length=255, null=True)),
                ('co_agency', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'academic_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('theme_list', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_list', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('url1', models.CharField(blank=True, max_length=255, null=True)),
                ('url2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'basic_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpertIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('profile', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('info_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'expert_intro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpinionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'opinion_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaperInfo',
            fields=[
                ('paper_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('authors', models.CharField(blank=True, max_length=255, null=True)),
                ('author1', models.CharField(blank=True, max_length=255, null=True)),
                ('author2', models.CharField(blank=True, max_length=255, null=True)),
                ('author3', models.CharField(blank=True, max_length=255, null=True)),
                ('author4', models.CharField(blank=True, max_length=255, null=True)),
                ('author5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'paper_info',
                'managed': False,
            },
        ),
    ]
