# Generated by Django 2.0.3 on 2018-08-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paperinfo',
            options={'managed': True},
        ),
    ]
