# Generated by Django 2.0.3 on 2018-08-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_auto_20180803_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'managed': True},
        ),
    ]
