# Generated by Django 2.0.3 on 2018-08-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_auto_20180803_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
