# Generated by Django 2.1 on 2018-09-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0006_auto_20180803_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicinfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'managed': True, 'verbose_name': '专家基本信息', 'verbose_name_plural': '专家基本信息'},
        ),
    ]
