# Generated by Django 2.1 on 2018-09-12 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0008_auto_20180912_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperinfo',
            name='author1',
        ),
        migrations.RemoveField(
            model_name='paperinfo',
            name='author2',
        ),
        migrations.RemoveField(
            model_name='paperinfo',
            name='author3',
        ),
        migrations.RemoveField(
            model_name='paperinfo',
            name='author4',
        ),
        migrations.RemoveField(
            model_name='paperinfo',
            name='author5',
        ),
        migrations.RemoveField(
            model_name='paperinfo',
            name='authors',
        ),
    ]
