# Generated by Django 2.1 on 2018-09-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0010_auto_20180912_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinfo',
            name='author1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
